### ISSUE TITLE
Documentation: Improve "how to use" section

### ISSUE THREAD

**Issue by yanmagale** [willmendesneto/ng-numbers-only#1]
Hi Will.

Great project. Thanks for share it.

How do you think about create section in README, about how to use the plugin and all possibilities?

**Comment by willmendesneto** [comment]
Thanks for the feedback @YanMagale. I'm closing this issue [in this commit](https://github.com/willmendesneto/ng-numbers-only/commit/a371f80224a90d791a4b7dc23326fc95af7a8c2b)

**Comment by yanmagale** [comment]
Great, thanks @willmendesneto
