### ISSUE TITLE
Firefox backspace not working 

### ISSUE THREAD

**Issue by tdantas** [willmendesneto/ng-numbers-only#3]
Hey @willmendesneto , thank you so much for you directive.

I've found a issue running on firefox ( my FF version is 49 )

go to your demo http://embed.plnkr.co/P5hoQ2/ and inside the `With precision` inputs try to use backspace.  I can't delete values using backspace key.

cheers mate

**Comment by willmendesneto** [comment]
Thanks for open this issue @tdantas, it's solved right now. Could you update your local package, please?

**Comment by tdantas** [comment]
hey @willmendesneto  thank you so much. 
working perfectly 👍 

cheers mate and keep rocking !
